export const movieData = [
  {
    adult: false,
    backdrop_path: "/DnjwdbjdR2c5MFhKv5ZSRf8rDU.jpg",
    genre_ids: [53, 27, 9648, 18],
    id: 546121,
    original_language: "en",
    original_title: "Run",
    overview:
      "Chloe, a teenager who is confined to a wheelchair, is homeschooled by her mother, Diane. Chloe soon becomes suspicious of her mother and begins to suspect that she may be harboring a dark secret.",
    popularity: 54.819,
    poster_path: "/mtDYMa2inpJjxq2DjELPXbtf02v.jpg",
    release_date: "2020-11-20",
    title: "Run",
    video: false,
    vote_average: 7.6,
    vote_count: 257,
    isWatch: true,
  },
  {
    adult: false,
    backdrop_path: "/c5SSBmh2pDFCuJLoWskOeoIxoE0.jpg",
    genre_ids: [28],
    id: 9399,
    original_language: "en",
    original_title: "Lionheart",
    overview:
      "Lyon Gaultier is a deserter in the Foreign Legion arriving in the USA entirely hard up. He finds his brother between life and death and his sister-in-law without the money needed to heal her husband and to maintain her child. To earn the money needed, Gaultier decides to take part in some very dangerous clandestine fights.",
    popularity: 42.238,
    poster_path: "/r9blY8BJR4FkWpvdbmmWuxPSc7z.jpg",
    release_date: "1990-06-07",
    title: "Lionheart",
    video: false,
    vote_average: 6.5,
    vote_count: 599,
    isWatch: false,
  },
  {
    adult: false,
    backdrop_path: "/79X8JkGxzc1tJMi0KxUSaPLooVg.jpg",
    genre_ids: [28, 878, 53],
    id: 274855,
    original_language: "en",
    original_title: "Geostorm",
    overview:
      "After an unprecedented series of natural disasters threatened the planet, the world's leaders came together to create an intricate network of satellites to control the global climate and keep everyone safe. But now, something has gone wrong: the system built to protect Earth is attacking it, and it becomes a race against the clock to uncover the real threat before a worldwide geostorm wipes out everything and everyone along with it.",
    popularity: 46.448,
    poster_path: "/nrsx0jEaBgXq4PWo7SooSnYJTv.jpg",
    release_date: "2017-10-13",
    title: "Geostorm",
    video: false,
    vote_average: 6,
    vote_count: 3334,
    isWatch: true,
  },
  {
    adult: false,
    backdrop_path: "/hUPgIibqZlwbhs4N08cPzzc4f5K.jpg",
    genre_ids: [28, 12, 14, 878],
    id: 127585,
    original_language: "en",
    original_title: "X-Men: Days of Future Past",
    overview:
      "The ultimate X-Men ensemble fights a war for the survival of the species across two time periods as they join forces with their younger selves in an epic battle that must change the past – to save our future.",
    popularity: 42.886,
    poster_path: "/bvN8iUpHyBIvniUk4e52SUZMA7Z.jpg",
    release_date: "2014-05-15",
    title: "X-Men: Days of Future Past",
    video: false,
    vote_average: 7.5,
    vote_count: 11985,
    isWatch: true,
  },

];
